### ISSUE TITLE
Slicing on connections is broken

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo_dl#24]
```
import matplotlib.pyplot as plt

import nengo
import nengo_dl

with nengo.Network() as model:
    stim = nengo.Node(output=lambda _: np.random.randn())
    p = nengo.Probe(stim[0], synapse=None)
    
for simulator in (nengo.Simulator, nengo_dl.Simulator):
    with simulator(model) as sim:
        sim.run(.1)

    plt.figure()
    plt.title(simulator.__module__)
    plt.plot(sim.trange(), sim.data[p])
    plt.show()
```

![nengo simulator](https://user-images.githubusercontent.com/5420057/32922217-296ec12a-caff-11e7-8775-56bd6f689f55.png)

![nengo_dl simulator](https://user-images.githubusercontent.com/5420057/32922218-2991da98-caff-11e7-870a-dac6964bdf3a.png)

The second graph's output is a flat `0`, when it should be the same as in the first graph. Changing `stim[0]` to `stim` gives the desired output.

This also happens when the slice happens on connections from `stim`.

**Comment by drasmuss** [comment]
Are you on `master`?  I don't get this there, I suspect this is the same bug fixed in 69155e2705677bd5589860532feb05001c7e23eb

**Comment by arvoelke** [comment]
This fixed this particular (reduced) example, but it's still happening in my larger model that uses slicing in multiple ways. I'll try to reduce that model yet again and post it here soon.

**Comment by arvoelke** [comment]
This seems to be a different problem, so closing and opening a new issue. Thanks!
